name: python-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - notebook
  - requests
  - pip
  - pip:
    - numpy>=2
    - pandas>=2
    - openpyxl
    - matplotlib
    - seaborn
    - scikit-learn
